// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC32HgzOXV2x1CyvupMb4_NvtGRGaiPV4I',
    appId: '1:977908129967:web:098ea09988fd424200345a',
    messagingSenderId: '977908129967',
    projectId: 'school-project-311f3',
    authDomain: 'school-project-311f3.firebaseapp.com',
    storageBucket: 'school-project-311f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnKQOyJY4OCP3jzAzoThzXU6wcPv8iuCA',
    appId: '1:977908129967:android:285aac347bbec1a000345a',
    messagingSenderId: '977908129967',
    projectId: 'school-project-311f3',
    storageBucket: 'school-project-311f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoJq6gufA5P8hL95jo7u-CvsNYtY803-c',
    appId: '1:977908129967:ios:971f82ab89dd5e5a00345a',
    messagingSenderId: '977908129967',
    projectId: 'school-project-311f3',
    storageBucket: 'school-project-311f3.firebasestorage.app',
    iosBundleId: 'com.example.profileCardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoJq6gufA5P8hL95jo7u-CvsNYtY803-c',
    appId: '1:977908129967:ios:971f82ab89dd5e5a00345a',
    messagingSenderId: '977908129967',
    projectId: 'school-project-311f3',
    storageBucket: 'school-project-311f3.firebasestorage.app',
    iosBundleId: 'com.example.profileCardApp',
  );
}
